import 'package:new_app/helpers/DisplayHelper.dart';

class SavedLocation {

  static List<String> CITIES = [
    "Abidjan",
    "Abu Dhabi",
    "Abuja",
    "Accra",
    "Addis Ababa",
    "Ahmedabad",
    "Aleppo",
    "Alexandria",
    "Algiers",
    "Almaty",
    "Amman",
    "Amsterdam",
    "Anchorage",
    "Andorra la Vella",
    "Ankara",
    "Antananarivo",
    "Apia",
    "Arnold",
    "Ashgabat",
    "Asmara",
    "Asuncion",
    "Athens",
    "Auckland",
    "Avarua",
    "Baghdad",
    "Baku",
    "Bamako",
    "Banda Aceh",
    "Bandar Seri Begawan",
    "Bandung",
    "Bangkok",
    "Bangui",
    "Banjul",
    "Barcelona",
    "Barranquilla",
    "Basrah",
    "Basse-Terre",
    "Basseterre",
    "Beijing",
    "Beirut",
    "Bekasi",
    "Belem",
    "Belgrade",
    "Belmopan",
    "Belo Horizonte",
    "Bengaluru",
    "Berlin",
    "Bern",
    "Bishkek",
    "Bissau",
    "Bogota",
    "Brasilia",
    "Bratislava",
    "Brazzaville",
    "Bridgetown",
    "Brisbane",
    "Brussels",
    "Bucharest",
    "Budapest",
    "Buenos Aires",
    "Bujumbura",
    "Bursa",
    "Busan",
    "Cairo",
    "Cali",
    "Caloocan",
    "Camayenne",
    "Canberra",
    "Cape Town",
    "Caracas",
    "Casablanca",
    "Castries",
    "Cayenne",
    "Charlotte Amalie",
    "Chengdu",
    "Chennai",
    "Chicago",
    "Chisinau",
    "Chittagong",
    "Chongqing",
    "Colombo",
    "Conakry",
    "Copenhagen",
    "Cordoba",
    "Curitiba",
    "Daegu",
    "Daejeon",
    "Dakar",
    "Dallas",
    "Damascus",
    "Dar es Salaam",
    "Delhi",
    "Denver",
    "Dhaka",
    "Dili",
    "Djibouti",
    "Dodoma",
    "Doha",
    "Dongguan",
    "Douala",
    "Douglas",
    "Dubai",
    "Dublin",
    "Durban",
    "Dushanbe",
    "Faisalabad",
    "Fort-de-France",
    "Fortaleza",
    "Freetown",
    "Fukuoka",
    "Funafuti",
    "Gaborone",
    "George Town",
    "Georgetown",
    "Gibraltar",
    "Gitega",
    "Giza",
    "Guadalajara",
    "Guangzhou",
    "Guatemala City",
    "Guayaquil",
    "Gujranwala",
    "Gustavia",
    "Gwangju",
    "Hamburg",
    "Hanoi",
    "Harare",
    "Havana",
    "Helsinki",
    "Ho Chi Minh City",
    "Hong Kong",
    "Honiara",
    "Honolulu",
    "Houston",
    "Hyderabad",
    "Hyderabad",
    "Ibadan",
    "Incheon",
    "Isfahan",
    "Islamabad",
    "Istanbul",
    "Izmir",
    "Jaipur",
    "Jakarta",
    "Jeddah",
    "Jerusalem",
    "Johannesburg",
    "Juarez",
    "Juba",
    "Kabul",
    "Kaduna",
    "Kampala",
    "Kano",
    "Kanpur",
    "Kaohsiung",
    "Karachi",
    "Karaj",
    "Kathmandu",
    "Kawasaki",
    "Kharkiv",
    "Khartoum",
    "Khulna",
    "Kigali",
    "Kingsburg",
    "Kingston",
    "Kingstown",
    "Kinshasa",
    "Kobe",
    "Kolkata",
    "Kota Bharu",
    "Kowloon",
    "Kuala Lumpur",
    "Kumasi",
    "Kuwait",
    "Kyiv",
    "Kyoto",
    "La Paz",
    "Lagos",
    "Lahore",
    "Libreville",
    "Lilongwe",
    "Lima",
    "Lisbon",
    "Ljubljana",
    "Lome",
    "London",
    "Los Angeles",
    "Luanda",
    "Lubumbashi",
    "Lusaka",
    "Luxembourg",
    "Macau",
    "Madrid",
    "Majuro",
    "Makassar",
    "Malabo",
    "Male",
    "Mamoudzou",
    "Managua",
    "Manama",
    "Manaus",
    "Manila",
    "Maputo",
    "Maracaibo",
    "Maracay",
    "Mariehamn",
    "Marigot",
    "Maseru",
    "Mashhad",
    "Mbabane",
    "Mecca",
    "Medan",
    "Medellin",
    "Medina",
    "Melbourne",
    "Mexico City",
    "Miami",
    "Minsk",
    "Mogadishu",
    "Monrovia",
    "Montevideo",
    "Montreal",
    "Moscow",
    "Mumbai",
    "Munich",
    "N'Djamena",
    "Nagoya",
    "Nairobi",
    "Nanchang",
    "Nanjing",
    "Nanning",
    "Nashville",
    "Nassau",
    "New Delhi",
    "New York",
    "Niamey",
    "Nicosia",
    "Nouakchott",
    "Noumea",
    "Novosibirsk",
    "Odesa",
    "Ouagadougou",
    "Oviedo",
    "Palermo",
    "Panama City",
    "Papeete",
    "Paramaribo",
    "Paris",
    "Patna",
    "Peking",
    "Perm",
    "Perth",
    "Peshawar",
    "Philadelphia",
    "Phnom Penh",
    "Phoenix",
    "Plovdiv",
    "Podgorica",
    "Port Louis",
    "Port Moresby",
    "Port-au-Prince",
    "Porto",
    "Porto Alegre",
    "Porto-Novo",
    "Prague",
    "Praia",
    "Providence",
    "Pune",
    "Pyongyang",
    "Qingdao",
    "Qom",
    "Quito",
    "Rabat",
    "Recife",
    "Reykjavik",
    "Riga",
    "Rio de Janeiro",
    "Riyadh",
    "Rome",
    "Rongcheng",
    "Rosario",
    "Rotterdam",
    "Rostov-on-Don",
    "Saigon",
    "Saint-Denis",
    "Saint-Paul",
    "Saint-Pierre",
    "Saint Vincent",
    "Salvador",
    "Samara",
    "San Diego",
    "San Francisco",
    "San Juan",
    "San Salvador",
    "Sanaa",
    "Santa Cruz",
    "Santiago",
    "Santo Domingo",
    "Sao Paulo",
    "Sapporo",
    "Seattle",
    "Sejong",
    "Seoul",
    "Shanghai",
    "Shantou",
    "Shenyang",
    "Shenzhen",
    "Shijiazhuang",
    "Singapore",
    "Skopje",
    "Sofia",
    "St. John's",
    "Stockholm",
    "Sucre",
    "Surabaya",
    "Surat",
    "Suva",
    "Sydney",
    "Tabriz",
    "Taichung",
    "Tainan",
    "Taipei",
    "Tallinn",
    "Tampa",
    "Tangier",
    "Tashkent",
    "Tbilisi",
    "Tehran",
    "Tel Aviv",
    "Thimphu",
    "Tianjin",
    "Tijuana",
    "Tirana",
    "Tokyo",
    "Toronto",
    "Tripoli",
    "Trujillo",
    "Tunis",
    "Turin",
    "Ulaanbaatar",
    "Urumqi",
    "Valencia",
    "Valletta",
    "Vancouver",
    "Vatican City",
    "Venice",
    "Veracruz",
    "Vienna",
    "Vientiane",
    "Vilnius",
    "Warsaw",
    "Washington, D.C.",
    "Wellington",
    "Winnipeg",
    "Wuhan",
    "Wuxi",
    "Xiamen",
    "Xian",
    "Yamoussoukro",
    "Yerevan",
    "Yokohama",
    "Zagreb",
    "Zapopan",
    "Zaragoza",
    "Zhangzhou",
    "Zhengzhou",
    "Zibo",
    "Zurich",
  ];

  static List<String> lowercaseList = CITIES.map((String element) => DisplayHelper.adjustCasing(element)).toList();

}
